export type PropertyType = "House" | "Apartment" | "Land"
export type PropertyStatus = "Available" | "Rented" | "Expired"

export interface Property {
  id: string
  name: string
  type: PropertyType
  location: string
  price: number
  description: string
  status: PropertyStatus
  tenant?: string
  startDate?: string
  endDate?: string
}

export const mockProperties: Property[] = [
  {
    id: "PROP-001",
    name: "Sunset Villa",
    type: "House",
    location: "Miami Beach, FL",
    price: 3500,
    description: "Luxury 4-bedroom villa with ocean view",
    status: "Rented",
    tenant: "John Smith",
    startDate: "2024-01-01",
    endDate: "2025-12-31",
  },
  {
    id: "PROP-002",
    name: "Downtown Loft",
    type: "Apartment",
    location: "Manhattan, NY",
    price: 2800,
    description: "Modern 2-bedroom loft in heart of city",
    status: "Rented",
    tenant: "Sarah Johnson",
    startDate: "2024-06-01",
    endDate: "2024-12-20",
  },
  {
    id: "PROP-003",
    name: "Garden Apartments",
    type: "Apartment",
    location: "Portland, OR",
    price: 1500,
    description: "Cozy 1-bedroom with garden access",
    status: "Available",
  },
  {
    id: "PROP-004",
    name: "Commercial Plot A",
    type: "Land",
    location: "Austin, TX",
    price: 5000,
    description: "2-acre commercial land near highway",
    status: "Rented",
    tenant: "TechCorp LLC",
    startDate: "2023-03-01",
    endDate: "2024-03-01",
  },
  {
    id: "PROP-005",
    name: "Lakeside Cottage",
    type: "House",
    location: "Lake Tahoe, CA",
    price: 2200,
    description: "Charming 3-bedroom cottage by the lake",
    status: "Available",
  },
  {
    id: "PROP-006",
    name: "Metro Studio",
    type: "Apartment",
    location: "San Francisco, CA",
    price: 1800,
    description: "Compact studio near transit hub",
    status: "Expired",
    tenant: "Mike Davis",
    startDate: "2023-01-01",
    endDate: "2024-01-01",
  },
  {
    id: "PROP-007",
    name: "Suburban Family Home",
    type: "House",
    location: "Dallas, TX",
    price: 2500,
    description: "4-bedroom home with large backyard",
    status: "Rented",
    tenant: "The Williams Family",
    startDate: "2024-03-15",
    endDate: "2025-03-15",
  },
  {
    id: "PROP-008",
    name: "Penthouse Suite",
    type: "Apartment",
    location: "Chicago, IL",
    price: 4200,
    description: "Luxury penthouse with skyline views",
    status: "Available",
  },
  {
    id: "PROP-009",
    name: "Farmland Parcel",
    type: "Land",
    location: "Iowa",
    price: 1200,
    description: "10-acre agricultural land",
    status: "Rented",
    tenant: "Green Farms Inc",
    startDate: "2024-01-01",
    endDate: "2026-01-01",
  },
  {
    id: "PROP-010",
    name: "Beach Bungalow",
    type: "House",
    location: "Malibu, CA",
    price: 5500,
    description: "Exclusive beachfront property",
    status: "Available",
  },
  {
    id: "PROP-011",
    name: "City Center Apartment",
    type: "Apartment",
    location: "Boston, MA",
    price: 2100,
    description: "2-bedroom in historic district",
    status: "Rented",
    tenant: "Emma Wilson",
    startDate: "2024-09-01",
    endDate: "2024-12-18",
  },
  {
    id: "PROP-012",
    name: "Mountain Cabin",
    type: "House",
    location: "Aspen, CO",
    price: 3200,
    description: "Rustic cabin with mountain views",
    status: "Available",
  },
  {
    id: "PROP-013",
    name: "Industrial Lot",
    type: "Land",
    location: "Detroit, MI",
    price: 3500,
    description: "5-acre industrial zoned land",
    status: "Expired",
    tenant: "BuildCo",
    startDate: "2022-06-01",
    endDate: "2024-06-01",
  },
  {
    id: "PROP-014",
    name: "Riverside Condo",
    type: "Apartment",
    location: "Seattle, WA",
    price: 2600,
    description: "3-bedroom condo with river views",
    status: "Rented",
    tenant: "David Chen",
    startDate: "2024-07-01",
    endDate: "2025-07-01",
  },
  {
    id: "PROP-015",
    name: "Historic Townhouse",
    type: "House",
    location: "Philadelphia, PA",
    price: 2900,
    description: "Restored Victorian townhouse",
    status: "Available",
  },
  {
    id: "PROP-016",
    name: "Student Housing Unit",
    type: "Apartment",
    location: "Ann Arbor, MI",
    price: 1200,
    description: "Furnished unit near campus",
    status: "Rented",
    tenant: "Lisa Brown",
    startDate: "2024-08-15",
    endDate: "2025-05-15",
  },
  {
    id: "PROP-017",
    name: "Golf Course Estate",
    type: "House",
    location: "Scottsdale, AZ",
    price: 6000,
    description: "5-bedroom luxury estate on golf course",
    status: "Available",
  },
  {
    id: "PROP-018",
    name: "Urban Loft Space",
    type: "Apartment",
    location: "Denver, CO",
    price: 1900,
    description: "Open-concept loft in arts district",
    status: "Available",
  },
  {
    id: "PROP-019",
    name: "Vineyard Property",
    type: "Land",
    location: "Napa Valley, CA",
    price: 8000,
    description: "15-acre vineyard with irrigation",
    status: "Rented",
    tenant: "Valley Wines",
    startDate: "2024-01-01",
    endDate: "2029-01-01",
  },
  {
    id: "PROP-020",
    name: "Waterfront Apartment",
    type: "Apartment",
    location: "Tampa, FL",
    price: 2300,
    description: "2-bedroom with marina access",
    status: "Rented",
    tenant: "Robert Taylor",
    startDate: "2024-11-01",
    endDate: "2024-12-25",
  },
]
